# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=by ssw 2021.12.29
LUCI_DEPENDS:=+homebox
LUCI_PKGARCH:=all
PKG_VERSION:=1.0.1
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

